package com.guowl.sign.http;

import java.util.HashMap;
import java.util.Map;

public class P1SignAndVerify {
	public static void main(String[] args) {
		p1sign();
//		p1signGM();
//		p1verify();
//		p1verifyGM();
	}

	public static void p1sign() {
		try {
			Map<String, String> params = new HashMap<String, String>();
			params.put("businessType", "P1Sign");
			params.put("ApplyID", "rsa");
			params.put("DSDigestALG", "sha1");
			params.put("Data_Format", "PlainData=2048");
			String data = "abcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowiei";
			HttpClient client = new HttpClient();
			client.connect(ServerUrl.URI, data, params);
		} catch (Exception e) {}
	}
	
	public static void p1signGM() {
		try {
			Map<String, String> params = new HashMap<String, String>();
			params.put("businessType", "P1Sign");
			params.put("ApplyID", "sm2");
			params.put("DSDigestALG", "sm3");
			params.put("Data_Format", "PlainData=2048");
			String data = "abcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowieiabcdefghiaiowiei";
			HttpClient client = new HttpClient();
			client.connect(ServerUrl.URI, data, params);
		} catch (Exception e) {}
	}

	public static void p1verify() {
		try {
			Map<String, String> params = new HashMap<String, String>();
			params.put("businessType", "P1Verify");
			params.put("VerifySignCertIssuerAndSN", "rsa");
			params.put("DSDigestALG", "sha1");
			params.put("Data_Format", "DSignData=172,PlainData=2732");
			String data = "c9y8evlnSpiESH3FwRrmStPLf8+ZLOquSGI8717VUWJhREsk9VfeE9jQu+IgKx9QDH5sYNSkrwTEaQ91CX1C8JB4J70NgidHgoOKhZyYefkhggSjH3LRNeDSyV7X/c1nY2uKsXcyzw5VkKuNRImcxOUttEq8jAhbiM5dW9JFdR8=YWJjZGVmZ2hpYWlvd2llaWFiY2RlZmdoaWFpb3dpZWlhYmNkZWZnaGlhaW93aWVpYWJjZGVmZ2hpYWlvd2llaWFiY2RlZmdoaWFpb3dpZWlhYmNkZWZnaGlhaW93aWVpYWJjZGVmZ2hpYWlvd2llaWFiY2RlZmdoaWFpb3dpZWlhYmNkZWZnaGlhaW93aWVpYWJjZGVmZ2hpYWlvd2llaWFiY2RlZmdoaWFpb3dpZWlhYmNkZWZnaGlhaW93aWVpYWJjZGVmZ2hpYWlvd2llaWFiY2RlZmdoaWFpb3dpZWlhYmNkZWZnaGlhaW93aWVpYWJjZGVmZ2hpYWlvd2llaWFiY2RlZmdoaWFpb3dpZWlhYmNkZWZnaGlhaW93aWVpYWJjZGVmZ2hpYWlvd2llaWFiY2RlZmdoaWFpb3dpZWlhYmNkZWZnaGlhaW93aWVpYWJjZGVmZ2hpYWlvd2llaWFiY2RlZmdoaWFpb3dpZWlhYmNkZWZnaGlhaW93aWVpYWJjZGVmZ2hpYWlvd2llaWFiY2RlZmdoaWFpb3dpZWlhYmNkZWZnaGlhaW93aWVpYWJjZGVmZ2hpYWlvd2llaWFiY2RlZmdoaWFpb3dpZWlhYmNkZWZnaGlhaW93aWVpYWJjZGVmZ2hpYWlvd2llaWFiY2RlZmdoaWFpb3dpZWlhYmNkZWZnaGlhaW93aWVpYWJjZGVmZ2hpYWlvd2llaWFiY2RlZmdoaWFpb3dpZWlhYmNkZWZnaGlhaW93aWVpYWJjZGVmZ2hpYWlvd2llaWFiY2RlZmdoaWFpb3dpZWlhYmNkZWZnaGlhaW93aWVpYWJjZGVmZ2hpYWlvd2llaWFiY2RlZmdoaWFpb3dpZWlhYmNkZWZnaGlhaW93aWVpYWJjZGVmZ2hpYWlvd2llaWFiY2RlZmdoaWFpb3dpZWlhYmNkZWZnaGlhaW93aWVpYWJjZGVmZ2hpYWlvd2llaWFiY2RlZmdoaWFpb3dpZWlhYmNkZWZnaGlhaW93aWVpYWJjZGVmZ2hpYWlvd2llaWFiY2RlZmdoaWFpb3dpZWlhYmNkZWZnaGlhaW93aWVpYWJjZGVmZ2hpYWlvd2llaWFiY2RlZmdoaWFpb3dpZWlhYmNkZWZnaGlhaW93aWVpYWJjZGVmZ2hpYWlvd2llaWFiY2RlZmdoaWFpb3dpZWlhYmNkZWZnaGlhaW93aWVpYWJjZGVmZ2hpYWlvd2llaWFiY2RlZmdoaWFpb3dpZWlhYmNkZWZnaGlhaW93aWVpYWJjZGVmZ2hpYWlvd2llaWFiY2RlZmdoaWFpb3dpZWlhYmNkZWZnaGlhaW93aWVpYWJjZGVmZ2hpYWlvd2llaWFiY2RlZmdoaWFpb3dpZWlhYmNkZWZnaGlhaW93aWVpYWJjZGVmZ2hpYWlvd2llaWFiY2RlZmdoaWFpb3dpZWlhYmNkZWZnaGlhaW93aWVpYWJjZGVmZ2hpYWlvd2llaWFiY2RlZmdoaWFpb3dpZWlhYmNkZWZnaGlhaW93aWVpYWJjZGVmZ2hpYWlvd2llaWFiY2RlZmdoaWFpb3dpZWlhYmNkZWZnaGlhaW93aWVpYWJjZGVmZ2hpYWlvd2llaWFiY2RlZmdoaWFpb3dpZWlhYmNkZWZnaGlhaW93aWVpYWJjZGVmZ2hpYWlvd2llaWFiY2RlZmdoaWFpb3dpZWlhYmNkZWZnaGlhaW93aWVpYWJjZGVmZ2hpYWlvd2llaWFiY2RlZmdoaWFpb3dpZWlhYmNkZWZnaGlhaW93aWVpYWJjZGVmZ2hpYWlvd2llaWFiY2RlZmdoaWFpb3dpZWlhYmNkZWZnaGlhaW93aWVpYWJjZGVmZ2hpYWlvd2llaWFiY2RlZmdoaWFpb3dpZWlhYmNkZWZnaGlhaW93aWVpYWJjZGVmZ2hpYWlvd2llaWFiY2RlZmdoaWFpb3dpZWlhYmNkZWZnaGlhaW93aWVpYWJjZGVmZ2hpYWlvd2llaWFiY2RlZmdoaWFpb3dpZWlhYmNkZWZnaGlhaW93aWVpYWJjZGVmZ2hpYWlvd2llaWFiY2RlZmdoaWFpb3dpZWlhYmNkZWZnaGlhaW93aWVpYWJjZGVmZ2hpYWlvd2llaWFiY2RlZmdoaWFpb3dpZWlhYmNkZWZnaGlhaW93aWVpYWJjZGVmZ2hpYWlvd2llaWFiY2RlZmdoaWFpb3dpZWlhYmNkZWZnaGlhaW93aWVpYWJjZGVmZ2hpYWlvd2llaWFiY2RlZmdoaWFpb3dpZWlhYmNkZWZnaGlhaW93aWVpYWJjZGVmZ2hpYWlvd2llaWFiY2RlZmdoaWFpb3dpZWlhYmNkZWZnaGlhaW93aWVpYWJjZGVmZ2hpYWlvd2llaWFiY2RlZmdoaWFpb3dpZWlhYmNkZWZnaGlhaW93aWVpYWJjZGVmZ2hpYWlvd2llaWFiY2RlZmdoaWFpb3dpZWlhYmNkZWZnaGlhaW93aWVpYWJjZGVmZ2hpYWlvd2llaWFiY2RlZmdoaWFpb3dpZWlhYmNkZWZnaGlhaW93aWVpYWJjZGVmZ2hpYWlvd2llaWFiY2RlZmdoaWFpb3dpZWlhYmNkZWZnaGlhaW93aWVpYWJjZGVmZ2hpYWlvd2llaWFiY2RlZmdoaWFpb3dpZWlhYmNkZWZnaGlhaW93aWVpYWJjZGVmZ2hpYWlvd2llaWFiY2RlZmdoaWFpb3dpZWk=";
			HttpClient client = new HttpClient();
			client.connect(ServerUrl.URI, data, params);
		} catch (Exception e) {}
	}
	
	public static void p1verifyGM() {
		try {
			Map<String, String> params = new HashMap<String, String>();
			params.put("businessType", "P1Verify");
			params.put("VerifySignCertIssuerAndSN", "sm2");
			params.put("DSDigestALG", "sm3");
			params.put("Data_Format", "DSignData=96,PlainData=2724");
			String data = "MEQCICt3xlnsOVi/Y+QDtu7b+On7bG8FbALXj5Xy7UrvvgvkAiA2O+m/tAHtVG+/UZQLn4u3UQtV7oN3liq/0DwY2E2IUQ==MTExMTExMTExMTExMTExMTExMTExMTExMXd3d3d3d3d3d3d3d3d3d3d3d3d3KComXiMoKiZeIyQpISspIykrIyQpKCo6PkZ9RX17OiI+Ij4/OkxQS0xGSkRIREZLREhGSkREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREQxMTExMTExMTExMTExMTExMTExMTExMTExd3d3d3d3d3d3d3d3d3d3d3d3d3coKiZeIygqJl4jJCkhKykjKSsjJCkoKjo+Rn1FfTExMTExMTExMTExMTExMTExMTExMTExMTF3d3d3d3d3d3d3d3d3d3d3d3d3dygqJl4jKComXiMkKSErKSMpKyMkKSgqOj5GfUV9ezoiPiI+PzpMUEtMRkpESERGS0RIRkpEREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTF3d3d3d3d3d3d3d3d3d3d3d3d3dygqJl4jKComXiMkKSErKSMpKyMkKSgqOj5GfUV9ezoiPiI+PzpMUEtMRkpESERGS0RIRkpEREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREMTExMTExMTExMTExMTExMTExMTExMTExMXd3d3d3d3d3d3d3d3d3d3d3d3d3KComXiMoKiZeIyQpISspIykrIyQpKCo6PkZ9RX0xMTExMTExMTExMTExMTExMTExMTExMTExd3d3d3d3d3d3d3d3d3d3d3d3d3coKiZeIygqJl4jJCkhKykjKSsjJCkoKjo+Rn1FfXs6Ij4iPj86TFBLTEZKREhERktESEZKRERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERDExMTExMTExMTExMTExMTExMTExMTExMTF3d3d3d3d3d3d3d3d3d3d3d3d3dygqJl4jKComXiMkKSErKSMpKyMkKSgqOj5GfUV9MTExMTExMTExMTExMTExd3d3d3d3d3d3d3d3d3d3d3d3d3coKiZeIygqJl4jJCkhKykjKSsjJCkoKjo+Rn1FfXd3d3d3d3d3d3d3d3d3d3d3d3d3KComXiMoKiZeIyQpISspIykrIyQpKCo6PkZ9RX0xMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExd3d3d3d3d3d3d3d3d3d3d3d3d3coKiZeIygqJl4jJCkhKykjKSsjJCkoKjo+Rn1FfXs6Ij4iPj86TFBLTEZKREhERktESEZKRERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERERDExMTExMTExMTExMTExMTExMTExMTExMTF3d3d3d3d3d3d3d3d3d3d3d3d3dygqJl4jKComXiMkKSErKSMpKyMkKSgqOj5GfUV9MTExMTExMTExMTExMTExMTExMTExMTExMXd3d3d3d3d3d3d3d3d3d3d3d3d3KComXiMoKiZeIyQpISspIykrIyQpKCo6PkZ9RX17OiI+Ij4/OkxQS0xGSkRIREZLREhGSkRERERERERERGREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTF3d3d3d3d3d3d3d3d3d3d3d3d3dygqJl4jKComXiMkKSErKSMpKyMkKSgqOj5GfUV9ezoiPiI+PzpMUEtMRkpESERGS0RIRkpEREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREMTExMTExMTExMTExMTExMTExMTExMTExMXd3d3d3d3d3d3d3d3d3d3d3d3d3KComXiMoKiZeIyQpISspIykrIyQpKCo6PkZ9RX0xMTExMTExMTExMTExMTExMTExMTExMTExd3d3d3d3d3d3d3d3d3d3d3d3d3coKiZeIygqJl4jJCkhKykjKSsjJCkoKjo+Rn1FfXs6Ij4iPj86TFBLTEa1w7XDtcNESEZKREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREREMTExMTExMTExMTExMTExMTExMTExMTExMXd3d3d3d3d3d3d3d3d3d3d3d3d3KComXiMoKiZeIyQpISspIykrIyQpKCo6PkZ9RX0xMTExMTExMTExMTExMTF3d3d3d3d3d3d3d3d3d3d3d3d3dygqJl4jKComXiMkKSErKSMpKyMkKSgqOj5GfUV9d3d3d3d3d3d3d3d3d3d3d3d3d3coKiZeIygqJl4jJCkhKykjKSsjJCk=";
			HttpClient client = new HttpClient();
			client.connect(ServerUrl.URI, data, params);
		} catch (Exception e) {}
	}
}
